SGLang.lang = $.extend(SGLang.lang,{
ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
ToolName: "Presentation Editor",
StartToolName: "Presentation Editor",
help: "Help",
PresentationUserManualChapterName: "Presentation",
Properties: "Properties",
Settings: "Settings",
ActionName: "Action Name",
RestartDynamicObject: "Restart Dynamic Object",
Show: "Show",
Hide: "Hide",
FlyTo: "Fly to",
Caption: "Caption",
Wait: "Wait",
Message: "Message",
SetSpeedFactor: "Set Speed Factor",
UndergroundMode: "Underground Mode",
SetTime: "Set Time",
PlayAnotherPresentation: "Play Presentation",
PlayRoute: "Play Route",
group: "Group",
object: "Object",
Seconds: "Seconds",
dropLocationObjectGroup: "Drag and drop a location, object or group from the Project Tree to here.",
dropLocationObject: "Drag and drop a location or an object from the Project Tree to here.",
dropGroup: "Drag and drop a group from the from the Project Tree to here.",
dropGroupOrObject: "Drag and drop an object or a group from the Project Tree to here.",
dropDynamicObject: "Drag and drop a dynamic object from the Project Tree to here.",
CurrentValue: "Current Value: ",
UseCurrentPosition: "Click to use current position",
asTheLocation: " as the location.",
EditMode: "Edit Mode",
PlayMode: "Play Mode",
actionDeletionConfirmation: "Are you sure you want to delete:",
multiDeletionConfirmation: "Are you sure you want to delete multiple actions?",
dropPresentationObject: "Drag and drop a presentation object from the Project Tree to here.",
SourcePresentationStep: "Step from external presentation",
copyAction: "Copy Action",
copyStep: "Copy Step",
pasteAction: "Paste Action",
pasteStep: "Paste Step",
playFromHere: "Play from Here",
JumpHere: "Jump Here",
edit: "Edit...",
delete: "Delete",
deleteItem: "Delete Item",
deleteMulti: "Delete Items",
rename: "Rename...",
removeWaitForClick: "Remove \"Wait for Click\"",
addWaitForClick: "Add \"Wait for Click\"",
points: "points",
selectPresentation: "No presentation was selected.",
editMessageObjectInTe: "Click here to edit the message object in the Create Message dialog.",
presentationCaptionStart: "Presentation: ",
on: "on",
off: "off",
GlobalSlopeMap: "Global Slope Map",
GlobalContoureMap: "Global Contour Map",
GlobalShadowMap: "Global Shadow Map",
Restart: "Restart",
Follow: "Follow",
StepWithoutClick: "without wait",
CreateMovie: "Create Movie",
Click: "Click",
CreateNewAction: "Create New Action",
FlytoLocationObject: "Fly to Location/Object",
ShowObjectorGroup: "Show Object or Group",
HideObjectorGroup: "Hide Object or Group",
SetWaitTime: "Set Wait Time",
SetTime: "Set Time",
CreateCaption: "Create Caption",
ClearCaption: "Clear Caption",
CreateMessageObject: "Create Message Object",
RestartDynamicObject: "Restart Dynamic Object",
PlayAnotherPresentation: "Play Another Presentation",
TurnUndergroundModeOnOff: "Turn Underground Mode On/Off",
RecordRoute: "Record Route",
ShowHideSlopeMap: "Show/Hide Slope Map",
ShowHideContourMap: "Show/Hide Contour Map",
ShowHideShadows: "Show/Hide Shadows",
end: ""
});

