SGLang.lang = $.extend(SGLang.lang,{
    ToolTitle: "SkylineGlobe - Skyline Software Systems, Inc.",
    ToolName: "Terrain Profile",
    help: "Help",
    Text0: "Cancel",
    Text1: "Delete Last Point",
    Text2: "Horizontal surface",
    Text3: "Surface",
    Text4: "3D surface",
    Text5: "Surface Sample Interval",
	Text6: "Create Measurement Objects",
	Text7: "Snapping",
	Text19: "",
	Text17: "Units",
	Text18: " meters",
	Text19: "Delete the measurement.", 
	Text20: "Delete the last measurement point.",
	Text21: "Snap the measurement points to edges, objects, and vertices.",
	Text22: "Calculate the area of the horizontal projection of your selection on the terrain.",
	Text23: "Calculate area on an arbitrary plane. The polygon’s orientation is determined by the first three points selected.",
	Text24: "Calculate the surface area of the selected region taking into account terrain contours.",
	Text27: "Calculate",
	Text28: "Surface Area",

	Text_Area:"Area",
	Text_Perimeter:"Perimeter",
	Text_squareMeter:"Square m",
	Text_squareKm:"Square Km",
	Text_squareFt:"Square ft",
	Text_squareMi:"Square mi",
	Text_in: "in",
	Text_ft: "ft",
	Text_mile: "mile",
	Text_mm: "mm",
	Text_cm: "cm",
	Text_meter: "m",
	Text_km: "km",



    Text999: ""
});